name: Update docs
on:
  push:
    branches: [main]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Call webhook
        run: |
        curl -X POST 
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token $REPO_TOKEN" \
          https://api.github.com/repos/pederpus/docs-playbook/dispatches \
          -d '{"event_type":"update_doc","client_payload":{}}'
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
